repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
      - id: check-added-large-files
        args: [--maxkb=1024]
      - id: check-json
      # - id: pretty-format-json
  # - repo: https://github.com/PyCQA/flake8
  #   rev: 6.1.0
  #   hooks:
  #     - id: flake8
  #       additional_dependencies:
  #         [
  #           "flake8-blind-except",
  #           "flake8-docstrings",
  #           "flake8-bugbear",
  #           "flake8-comprehensions",
  #           "flake8-docstrings",
  #           "flake8-implicit-str-concat",
  #           "pydocstyle>=5.0.0",
  #         ]
  #       exclude: ^tests/test_cases/no_closing_bracket\.py$
  #       args: [--max-line-length=120]
  # - repo: https://github.com/psf/black
  #   rev: 23.9.1
  #   hooks:
  #     - id: black
  #       exclude: tests/
  #       args: [--check, --line-length=120]
  # - repo: https://github.com/pycqa/isort
  #   rev: 5.11.2
  #   hooks:
  #     - id: isort
  #       name: isort (python)
